### ISSUE TITLE
과제 피드백 드립니다.

### ISSUE THREAD

**Issue by joshua1988** [groovypark/todolist#4]
안녕하세요 수빈님 :)

어제 코드를 고치고 정리해서 PR 드리려 했는데 이미 다 확인하셨더라구요. 그새 벌써 확인하시고 다 척척 머지까지 하신 걸 보니 참 대단하신 것 같다는 생각이 들어요 :)

추가적으로 코드를 더 봐드리고 싶었는데, 일단 이 시점에서는 코드 상의 리뷰 보다는 전체적인 피드백을 드리는 게 좋을 것 같네요 :)

## 컴포넌트 구조
수빈님이 제출해주신 과제를 살펴보니까 컴포넌트가 루트 컴포넌트(App.vue)를 제외하고도
TodoApp - TodoContainer - TodoList의 세 레벨로 구성되어 있더라구요.

컴포넌트 네이밍에서 추론되는 건 이미 리액트를 어느 정도 경험하셨던 것 같은데, 거기에 더불어 인상적인 점은 Container / Presentational 컴포넌트를 잘 나누어서 깔끔하게 구현하셨다 라는 점입니다. 👍 

요즘 프런트엔드 시장에서 대중적인 컴포넌트에 대한 이해도가 높으신 것 같았어요 :)

이미 잘 구현해놓으셨지만, 제가 한 가지 의견을 드리고 싶은 점이 있어요.
TodoContainer가 이름은 Container지만 실제로는 Container의 역할을 TodoApp에서 하고 있는 것처럼 보입니다. 오히려 TodoContainer에서는 props랑 events를 전달하는 매개체 역할만 하고 있고, clearCompleted()나 adjustFilter() 모두 분리하지 않고도 충분히 TodoApp에서 기능할 수 있다고 생각했어요 :)

나중에 협업이라든지 유지 보수 관점에서 봤을 때도 최대한 코드의 구조가 간결하고 목적이 명확한 게 좋을 것 같다는 생각입니다 :) 제가 TodoList에서 events와 props가 아닌 이벤트 버스를 사용한 이유도 실은 TodoContainer에서 불필요하게 코드들이 공간을 차지하고 있다고 생각했기 때문이에요 :)

여튼 중요한 건 이미 잘 구현해주셨고, 제 생각을 공유드린 것뿐이니 참고만 해주셔도 될 것 같아요 :)

## 코드의 일관성
앞에서 말씀드린 것처럼 수빈님의 높은 컴포넌트의 이해도에도 놀랐지만, 전체적으로 네이밍을 깔끔하게 하시고 정갈하게 짜시는 모습에 또 놀랐습니다 :) 개인적으로 제가 좋아하는 코딩 스타일을 갖고 계신 것 같아요 👍 
그래서 수빈님께 한 가지 조언을 드리자면 전체적으로 코드를 조금만 더 일관되게 짜시면 좋을 것 같습니다 :)

예를 들면, 다음 두 가지가 가장 눈에 띄었습니다.
- ES6와 ES5의 혼용
- 세미 콜론 사용 / 미사용

어느 부분에서는 ES6를 사용하시고, 어느 부분에서는 그렇지 않으시더라구요. 혹시 아직 덜 익숙하신 거라면 이번에 저희 수업에서 나머지 ES6도 다 마스터하시면 좋을 것 같습니다 :) 아 그리고 ES6 얘기 나온 김에 먼저 하나 공유해드릴게요. [ ES6 기본 문법](https://joshua1988.github.io/es6-online-book/)

세미 콜론 역시 일관되게 다 붙이시든지 아니면 다 사용하지 않으시든지 하시면 좋을 것 같습니다 :)
개인적으로는 ESLint를 사용해보시고 그 권고 사항에 맞게 코딩하는 습관을 들이시는 것도 좋을 것 같아요.

## 모듈화
아마 제가 피드백 드린 것 보시면 저는 ES6의 modules를 최대한 활용해 Vue의 컴포넌트에 들어가지 않고 별도로 분리해도 되는 코드들은 밖으로 분리한 것을 보실 수 있을거에요. 이러한 부분은 수빈님께서 코드를 잘못 짜셨다기보다 제가 그냥 선호하는 방식이기 때문에 아 이렇게 짤 수도 있겠구나 라고 참고만 하셔도 좋을 것 같아요 :)

---
이상입니다 수빈님,
과제하느라 고생 많으셨구요.
열심히 따라와주셔서 감사드립니다 :)

장기효 드림

**Comment by groovypark** [comment]
상세한 피드백 감사드립니다!!
